name: build-macos
on:
  workflow_call:
    inputs:
      commit:
        type: string
        default: "master"

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        arch: [win64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            .ccache
            wine
          key:
            cache-macos-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            cache-macos-${{ matrix.arch }}

      - name: Build
        run: |
          $PWD/build-macos ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-${{ matrix.arch }}
          path: usr
