name: nightly
on:
  push:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build-linux:
    if: ${{ endsWith(github.repository, 'winetest') }}
    uses: ./.github/workflows/build-linux.yml
    with:
      commit: master

  build-macos:
    if: ${{ endsWith(github.repository, 'winetest') }}
    uses: ./.github/workflows/build-macos.yml
    with:
      commit: master

  tests-linux:
    if: ${{ endsWith(github.repository, 'winetest') }}
    needs: build-linux
    uses: ./.github/workflows/tests-linux.yml
    with:
      event: ${{ github.event_name }}

  tests-macos:
    if: ${{ endsWith(github.repository, 'winetest') }}
    needs: build-macos
    uses: ./.github/workflows/tests-macos.yml
    with:
      event: ${{ github.event_name }}

  tests-windows:
    if: ${{ endsWith(github.repository, 'winetest') }}
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - run: |
          gh -R rbernon/winetest-w7e        workflow run windows -f run_id=${{ github.run_id }} -f event=${{ github.event_name }} -f install=7e   -f version=w7e64 ||:
          gh -R rbernon/winetest-w81e       workflow run windows -f run_id=${{ github.run_id }} -f event=${{ github.event_name }} -f install=8e   -f version=w81e64 ||:
          gh -R rbernon/winetest-w10pro     workflow run windows -f run_id=${{ github.run_id }} -f event=${{ github.event_name }} -f install=10   -f version=w10pro64 ||:
          gh -R rbernon/winetest-w10ltsc    workflow run windows -f run_id=${{ github.run_id }} -f event=${{ github.event_name }} -f install=10l  -f version=w10ltsc64 ||:
          gh -R rbernon/winetest-w11pro     workflow run windows -f run_id=${{ github.run_id }} -f event=${{ github.event_name }} -f install=11   -f version=w11pro64 ||:
          gh -R rbernon/winetest-w11ltsc    workflow run windows -f run_id=${{ github.run_id }} -f event=${{ github.event_name }} -f install=11l  -f version=w11ltsc64 ||:

  clean:
    if: always()
    needs: [tests-linux, tests-macos, tests-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
